language: python
python:
  - "3.4"
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - install-tt.sh
# command to run tests
script: 
    - coverage run --source=MyCapytain setup.py test
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi
branches:
  only:
    - master